### ISSUE TITLE
Offer a modernized version of the formatter

### ISSUE THREAD

**Issue by Frotty** [fpirola/java-formatter-eclipse-mars#2]
Hi again, @fpirola 

I think this formatter is a nice template, but not very well fit for modern application where Full HD and 2 monitors are the standard.
Stuff like 80 chars line width is just not plausible nowadays and some things aren't formatted so well.

I have made following adjustments:
- Maximum line width set to 140
- Maximum line width for comments/javadoc set to 140
- Enabled on/off tags **(this should be activated to not break people's formatting!!)**
- Line Wrapping policy of Qualified invocations set to "Wrap all elements, except first element if not necessary"
- Change line wrapping for enums: wrap all elements, every element on a new line + force split
- Change line wrapping for expressions: wrap all ements, except first element if not necessary

I think these are the most important changes.
It would offer a more out-of-the-box experience, unlike the current one, which we had to modify quite a lot to fit our needs.

As I said, this should only be an option and you can keep the original one.

**Comment by fpirola** [comment]
Hi @Frotty,

sorry for the late response and thank you for your feedback.

Well, I will try to reply to your points:

**1. & 2. :** I set the limit to 80 characters per line in order to be compliance with the default value set in checkstyle, [for an example project please refer to this post](https://github.com/fpirola/maven-example-project-for-java). I personally I think that 80 chars is normally good value for this reasons:
_**a)**_ you can easily compare code side by side by widescreen monitors;
_**b)**_ if you have very long lines, you also tend to have lines that vary in length a lot, leading to a lot of wasted screen and is less readable;
_**c)**_ very long lines generally means that you have very complicated lines, deep indendation, or that you have very long identifiers. All of these can be a problem. Complicated lines are probably doing too much; if you can break it down into several simpler lines, you probably should. Deep indentation means that you're probably nesting too many loops and conditionals, which can make your code flow confusing; considering refactoring into several functions. And if your identifiers are too long, it can make reading your code very difficult. 

That said, the limit set per lines is a project/team decision. In some projects you probably set more than 80 chars per lines but remember to not exceed the limit size. So for this parameter you can consider this formatter as a template.

**3. :** Turn off&on formatting influence checkstyle warning/errors, so this change will be compliance with checkstyle

**4. & 5. & 6. :** Probably formatter in these cases it is not working very well. In future I will create a test project, and obviously upload to this repository, in order to test this cases and fix issues.

Best regards,
Fabio

**Comment by Frotty** [comment]
Okay then it's more checkstyle fault I suppose ;)
80 Characters is not feasible for modern java code imho, unless you use undescriptive names for methods and variables. But if you do that at work your colleagues will slaughter you.

Anyways, I'm using IntelliJ IDEA now, so I'm not really using this anymore, but thanks for the response.

**Comment by fpirola** [comment]
Hi @Frotty,
3. & 4. & 5. & 6. are now resolved with Java formatter version 2.0 947eef5e0b86fa1940c50c8b95d4f0168981c373
Thanks for your feedback,

Best Regards
Fabio
